### PR TITLE
Pass additional environment information to tests, compress reports

### PR DESCRIPTION
**Pull request by skipi**
This PR introduces two significant changes to the test results:

## New Field - semaphore_env:

- We've introduced a new field in the test case named semaphore_env. This field is designed to hold detailed information about the test runtime environment, aiding significantly in debugging and enhancing our understanding of test behaviors across different setups.

## Default GZip Compression for Reports:

- To manage the increased size of reports more efficiently, we are enabling GZip compression by default for all reports.
- In an effort to make this transition as seamless as possible, we have decided to keep the report names unchanged, i.e., they will not include the .gz extension traditionally associated with GZip files.
- Despite the absence of the .gz extension, rest assured that these reports are indeed compressed. We understand that this is a departure from the standard convention, and we have updated our README file with detailed information about this change.

### CODE REVIEW

**Review by ralopes — DISMISSED** [review]

**Review by ralopes — DISMISSED** [review]

**Review by hamir-suspect — DISMISSED** [review]
Changes in parsers tests seem huge because of `CommonParse`, is there big difference between what we parse in `CommonParse` test cases, maybe the definition of this can be wrapped in a single function?

**Comment by skipi** [comment]
> Changes in parsers tests seem huge because of `CommonParse`, is there big difference between what we parse in `CommonParse` test cases, maybe the definition of this can be wrapped in a single function?

Most of those changes are related to the code formatting. I didn't want to have everything in one line(as we had this in the past). 
The idea behind spec extraction is to have a defined behavior for specific XML inputs.
It's not really possible to have common expectations for these parsers, as there are subtle differences in how every parser handles some fields. In the next iterations, I'll try to figure out some better way of testing these parsers because I don't like how they're structured now as well(it's better than it was, but I think there's more to be done there)

**Comment by caius** [comment]
@skipi @ralopes FYI this is the exact opposite of backwards compatibility from an end user's perspective. It's taken me a while debugging why my JSON parsing is breaking to realise you're writing something **other** than JSON into a file named `UUID.json`. If the json file had vanished I'd have been able to debug that error much easier, as `UUID.json.gz` would exist to show it now had a compressed version instead.

The note in the Readme is incorrect if you view it from the above perspective, but at least there is a note. The Semaphore Changelog on your site doesn't appear to mention this breaking change either.

Easy enough to add a `gunzip -c UUID.json` into my pipeline to handle this now, but quite difficult to unpick from "file appears the same but contents unparseable".

**Comment by skipi** [comment]
> @skipi @ralopes FYI this is the exact opposite of backwards compatibility from an end user's perspective. It's taken me a while debugging why my JSON parsing is breaking to realise you're writing something **other** than JSON into a file named `UUID.json`. If the json file had vanished I'd have been able to debug that error much easier, as `UUID.json.gz` would exist to show it now had a compressed version instead.
> 
> The note in the Readme is incorrect if you view it from the above perspective, but at least there is a note. The Semaphore Changelog on your site doesn't appear to mention this breaking change either.
> 
> ~Easy enough to add a `gunzip -c UUID.json` into my pipeline to handle this now, but quite difficult to unpick from "file appears the same but contents unparseable".~
> 
> Edit: turns out it's not so simple to work around with `gunzip` because `gzip` validates the filenames and expects to strip a suffix when decompressing a file.
> 
> ```
> semaphore@semaphore-vm:~$ gunzip ${SEMAPHORE_PIPELINE_0_ARTEFACT_ID}.json
> gzip: b95720c9-9d1f-4bf5-9663-efc0a00f79a9.json: unknown suffix -- ignored
> ```
> 
> At least I've learned more about how `gzip` functions today, always something new to learn!

@caius, I sincerely apologize for the inconvenience and time you spent debugging due to this change. Your feedback is extremely valuable, and you're absolutely correct – from a user's standpoint, this modification constitutes a significant change.

My initial explanation was framed from the perspective of our internal semaphore processes that interact with these reports. Our long-term goal is to transition exclusively to using the gzipped versions of these reports during transit, and they will be appropriately named with the correct extension.

I recognize the importance of transparency in such transitions, and I assure you that we will improve our communication about such changes in the future. Your experience has been a crucial learning point for us, and we are committed to ensuring a smoother and more informed user experience going forward.

Thank you again for your understanding and for bringing this to our attention.

**Comment by caius** [comment]
@skipi thanks for acknowledging this, and can I just say how much I appreciate your tooling being openly viewable on GitHub as it massively aids debugging behaviours. Totally understand your point this was written in the context of an internal change though.

Also appreciate you may not have realised end-users were using that file directly too, as documented it's just a side effect of how to get the unified data into the tests UI. We want to collect all the timing data into a different format (for [knapsack](https://github.com/KnapsackPro/knapsack)) and realised we can just reformat that file. All fixed now, just added a `mv`, `gunzip` in the pipeline first now. At least it was a cut-over change too, so everything changed at once. Made it much easier to debug 😁

**Pull request merged**
